### Register
POST http://localhost:5000/api/auth/register
Content-Type: application/json

{
  "name": "Demo User",
  "email": "demo@example.com",
  "password": "password123"
}

### Login
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
  "email": "demo@example.com",
  "password": "password123"
}
### Protected
GET http://localhost:5000/api/test/protected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5MTFmMmUxODVlMmVhYTE4YTdhMjU0MiIsImVtYWlsIjoiZGVtb0BleGFtcGxlLmNvbSIsImlhdCI6MTc2Mjc4NDAwMywiZXhwIjoxNzYyNzg3NjAzfQ.g9vgIrYMYNIEd5Yol6XzaA6827T0JuzCvfMED13q5cM

